name : spider_2
services:
  order:
    container_name: order
    image: revanth7733/order_service:latest
    ports:
      - "3003:3003"
    depends_on:
      - rabbitmq
  
  product:
    container_name: product
    image: revanth7733/product_service:latest
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq

  user:
    container_name: user
    image: revanth7733/user_service:latest
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
      - redis
    
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13.4-alpine
    volumes:
      - rabbitmq_db:/var/lib/rabbitmq

  redis:
    container_name: redis
    image: redis:7.2.5-alpine
    volumes:
      - redis_db:/data
  
volumes:
  rabbitmq_db:
  redis_db: