name : devops_2
services:
  order:
    container_name: order
    image: revanth7733/order_service:latest
    depends_on:
      rabbitmq : 
        condition: service_healthy
  
  product:
    container_name: product
    image: revanth7733/product_service:latest
    depends_on:
      rabbitmq : 
        condition: service_healthy

  user:
    container_name: user
    image: revanth7733/user_service:latest
    depends_on:
      rabbitmq : 
        condition: service_healthy
      redis : 
        condition: service_healthy
    
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13.4-alpine
    volumes:
      - rabbitmq_db:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 3s
      timeout: 3s
      retries: 5

  redis:
    container_name: redis
    image: redis:7.2.5-alpine
    volumes:
      - redis_db:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 5
  
  nginx:
    container_name: nginx
    image: revanth7733/nginx_rev_proxy:latest
    ports:
      - "3000:80"
    depends_on:
      - order
      - product
      - user

volumes:
  rabbitmq_db:
  redis_db: