name : Docker build and push
on : [push]
jobs : 
    docker_build_push :
        runs-on : ubuntu-latest
        steps : 
        -   name : Checkout
            uses : actions/checkout@v4
        
        -   name : Docker Login
            uses : docker/login-action@v3
            with :
                username : ${{ secrets.DOCKER_USERNAME }}
                password : ${{ secrets.DOCKER_PAT }}
        
        -   name : Build alpine with nodejs and npm
            uses : docker/build-push-action@v6
            with :
                context : ./docker_files/
                file : ./docker_files/alpine_node
                push : false
                tags : alpine_node:latest

        -   name : Build and push ngnix_rev_proxy
            uses : docker/build-push-action@v6
            with :
                context : ./docker_files/
                file : ./docker_files/ngnix_rev_proxy
                push : true
                tags : ${{ secrets.DOCKER_USERNAME }}/ngnix_rev_proxy:latest

        -   name : Build and push user_service
            uses : docker/build-push-action@v6
            with :
                context : ./docker_files/
                file : ./docker_files/user_dockerfile
                push : true
                tags : ${{ secrets.DOCKER_USERNAME }}/user_service:latest

        -   name : Build and push product_service
            uses : docker/build-push-action@v6
            with :
                context : ./docker_files/
                file : ./docker_files/product_dockerfile
                push : true
                tags : ${{ secrets.DOCKER_USERNAME }}/product_service:latest

        -   name : Build and push order_service
            uses : docker/build-push-action@v6
            with :
                context : ./docker_files/
                file : ./docker_files/order_dockerfile
                push : true
                tags : ${{ secrets.DOCKER_USERNAME }}/order_service:latest
    
