name : Docker build and push
on : [push]
jobs : 
    build :
        runs-on : ubuntu-latest
        steps : 
        -   name : Checkout
            uses : actions/checkout@v4
        
        -   name : Docker Login
            uses : docker/login-action@v3
            with :
                username : ${{ secrets.DOCKER_USERNAME }}
                password : ${{ secrets.DOCKER_PAT }}

        -   name : Build and push user_service
            uses : docker/build-push-action@v6
            with :
                context : ./docker_files
                file : user_dockerfile
                push : true
                tags : ${{ secrets.DOCKER_USERNAME }}/user_service:latest

        -   name : Build and push product_service
            uses : docker/build-push-action@v6
            with :
                context : ./docker_files
                file : product_dockerfile
                push : true
                tags : ${{ secrets.DOCKER_USERNAME }}/product_service:latest

        -   name : Build and push order_service
            uses : docker/build-push-action@v6
            with :
                context : ./docker_files
                file : order_dockerfile
                push : true
                tags : ${{ secrets.DOCKER_USERNAME }}/order_service:latest
    
